config/routes.rb
Rails.application.routes.draw do
  resources :intervention1s
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/graphql", to: "graphql#execute"
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'RocketElevatorsWebpage_Residential.html' => 'pages#RocketElevatorsWebpage_Residential.html'
  get 'RocketElevatorsWebpage_Corporate.html' => 'pages#RocketElevatorsWebpage_Corporate.html'
  get 'RocketElevatorsWebpage_submission.html' => 'pages#RocketElevatorsWebpage_submission.html'
  get 'login.html' => 'pages#login.html'
  get 'employee' => 'pages#admin/login'
  get "quotes" => "pages#index"
  get "/charts" => 'charts#charts'
  get "google_map" => 'google_maps#index'
  get "/watson" => 'watson#watson'
  get "RockREST" => 'pages#RockRest'
  # get "tasks" => 'intervention1s_controller#buildings'

  resources :google_maps
  resources :transcriptions
  resources :quotes
  resources :leads
  resources :intervention1s  

end

app/models/quote.rb
class Quote < ApplicationRecord

    # after_create :createTicket

    def createTicket

        puts "creating a ticket"

        client = ZendeskAPI::Client.new do |config|
          
            config.url = "https://rocketelevatorshuge.zendesk.com/api/v2" # e.g. https://mydesk.zendesk.com/api/v2
          
            config.username = "rocketelevatorhuge@gmail.com"
            config.token = ENV['zendeskApi']
          
            # Retry uses middleware to notify the user
            # when hitting the rate limit, sleep automatically,
            # then retry the request.
            config.retry = true
          
            # Logger prints to STDERR by default, to e.g. print to stdout:
            require 'logger'
            config.logger = Logger.new(STDOUT)
        
        end
      
        client.tickets.create!(:subject => "QUOTE FOR: #{self.full_name} from #{self.business_name}",
        :type => "task", :comment => { :value => "The contact #{self.full_name} from company #{self.business_name} can be reached at email #{self.email} and at phone number #{self.phone_number}.
        \n \n The client require a quote for a #{self.building_type} building with a #{self.quality} installation.
        \n #{self.number_elevator} elevators are initially suggested for construction with for a total price of #{self.total_price}$."},
        :priority => "urgent")
        
    end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

      if params[:building_type] == "Residential" 
        @quote.quality = params[:quality]
        @quote.elevator_price = params[:elevator_price]
        @quote.installation_price = params[:installation_price]
        @quote.number_elevator = params[:number_elevator]
        @quote.total_price = params[:total_price]
      end

      if params[:building_type] == "Commercial" 
        @quote.quality = params[:quality]
        @quote.number_floor = params[:number_floor2]
        @quote.number_basement = params[:number_basement2]
        @quote.number_parking_space = params[:number_parking_space2]
        @quote.elevator_price = params[:elevator_price]
        @quote.installation_price = params[:installation_price]
        @quote.number_elevator = params[:number_elevator]
        @quote.total_price = params[:total_price]
      end

      if params[:building_type] == "Corporate" 
        @quote.quality = params[:quality]
        @quote.number_floor = params[:number_floor3]
        @quote.number_basement = params[:number_basement3]
        @quote.number_of_distinct_business = params[:number_of_distinct_business3]
        @quote.number_parking_space = params[:number_parking_space3]
        @quote.maximum_occupant_per_floor = params[:maximum_occupant_per_floor3]
        @quote.elevator_price = params[:elevator_price]
        @quote.installation_price = params[:installation_price]
        @quote.number_elevator = params[:number_elevator]
        @quote.total_price = params[:total_price]
      end

      if params[:building_type] == "Hybrid" 
        @quote.quality = params[:quality]
        @quote.number_floor = params[:number_floor4]
        @quote.number_basement = params[:number_basement4]
        @quote.number_of_distinct_business = params[:number_of_distinct_business4]
        @quote.number_parking_space = params[:number_parking_space4]
        @quote.maximum_occupant_per_floor = params[:maximum_occupant_per_floor4]
        @quote.elevator_price = params[:elevator_price]
        @quote.installation_price = params[:installation_price]
        @quote.number_elevator = params[:number_elevator]
        @quote.total_price = params[:total_price]
      end





    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'QUOTE WAS SUCCESSFULLY SENT' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end

    @quote.createTicket


  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'QUOTE WAS SUCCESSFULLY UPDATED.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'QUOTE WAS SUCCESSFULLY DESTROYED.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.permit(:full_name, :phone_number, :building_type, 
        :number_floor, :number_appartment, :number_basement, 
        :number_of_trade_market, :number_parking_space, 
        :number_of_elevators_cage, :number_of_distinct_business, 
        :maximum_occupant_per_floor, :hour_of_activity, 
        :elevator_price, :installation_price, :number_elevator, 
        :quality, :business_name, :email)
      # params.require(:quote).permit()
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :new %>
    <%= form.text_field :new %>
  </div>

  <div class="field">
    <%= form.label :create %>
    <%= form.text_field :create %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/_partial.html.erb
<div id="wrapper">

		<div id="header" class="dark navbar-toggleable-md sticky clearfix shadow-before-1">

			<!-- TOP NAV -->
			<header id="topNav">
				<div class="container">

					<!-- Mobile Menu Button -->
					<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
						<i class="fa fa-bars"></i>
					</button>

					<!-- BUTTONS -->
					<ul class="float-right nav nav-pills nav-second-main">




					</ul>
					<!-- /BUTTONS -->


					<!-- Logo -->
					<a class="submenu-dark" href="index.html">
						<%= image_tag("R22.png", :alt => "RocketElevator-logo", :class => "img-fluid", :width =>"150", :height =>"60") %>
					</a>

					<div class="navbar-collapse collapse float-right nav-main-collapse">
						<nav class="nav-main">

							<ul id="topMain" class="nav nav-pills nav-main">
								<li>
									<!-- HOME -->
									<a href="/">
										HOME
									</a>

								</li>

								<li>
									<!-- SERVICES -->
									<a href="/#to_services">
										SERVICES
									</a>
									<ul class="dropdown-menu">
										<li><a href="/RocketElevatorsWebpage_Residential.html">Residential offers</a></li>
										<li><a href="/RocketElevatorsWebpage_Corporate.html">Corporate offers</a></li>
										<li><a href="/RocketElevatorsWebpage_submission.html">Submission</a></li>
									</ul>

								<li>
									<!-- PORTFOLIO -->
									<a href="/#to_portfolio">
										PORTFOLIO
									</a>

								<li>
									<!-- NEWS -->
									<a href="/#to_news">
										NEWS
									</a>

								</li>


								<li>
									<!-- CLIENTS -->
									<a href="/#to_clients">
										CLIENTS
									</a>

								</li>

								<li>
									<!-- ADMIN -->
									<a href="/admins">LOGIN</a>

								</li>

								<li>
									<!-- CONTACT US -->
									<a href="/#footer">
										CONTACT US
									</a>

								</li>


							</ul>

						</nav>
					</div>

				</div>
			</header>
			<!-- /Top Nav -->

		</div>


	<section class="btn btn-xlg btn-primary fs-20 fullwidth m-0 rad-40 p-40 " style="background-image: url('/assets/AdobeStock_103570025.jpeg');">
		<span class="font-lato fs-30" style="color:rgb(300, 300, 300)">
			For the best elevators,
			<strong> Rocket Elevators ! </strong>
		</span>
	</section>

<section class= "dark">
    <div class="dark col-md-3">

						<h2>ABOUT US</h2>

						<p>
							Rocket Elevator is a dedicated compagny who listen his customers. Our slogan is elevate safety, speed and style.
							This is exactly the kind of elevator we make.
						</p>

						<hr />

						<p>
							<span class="block"><strong><i class="fa fa-map-marker"></i> Address:</strong> <a target="new" href="https://www.google.com/maps/place/725+Boulevard+Lebourgneuf,+Qu%C3%A9bec,+QC+G2J+1S1/@46.8428435,-71.2818835,17z/data=!3m1!4b1!4m5!3m4!1s0x4cb897ddc2cec043:0xd450d4d0da014cc8!8m2!3d46.8428399!4d-71.2796948">
									725 Boulevard Lebourgneuf, </a>
								Québec, QC G2J 1S1</span>
							<span class="block"><strong><i class="fa fa-phone"></i> Phone:</strong> <a href="tel:418-580-7055">418-580-7055</a></span>
							<span class="block"><strong><i class="fa fa-envelope"></i> Email:</strong> <a target="new" href="https://imgur.com/gallery/TbKAF1l">support@codeboxx.biz</a></span>
						</p>

						<hr />

						<h4 class="font300">Business Hours</h4>
						<p>
							<span class="block"><strong>Monday - Friday:</strong> 8am to 6pm</span>
							<span class="block"><strong>Saturday:</strong> 10am to 2pm</span>
							<span class="block"><strong>Sunday:</strong> Closed</span>
						</p>

						<div class="mapouter">
							<div class="gmap_canvas"><iframe width="300" height="300" id="gmap_canvas" src="https://maps.google.com/maps?q=725%20Boulevard%20Lebourgneuf%2C%20Qu%C3%A9bec%2C%20QC%20G2J%201S1&t=&z=13&ie=UTF8&iwloc=&output=embed"
								 frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.embedgooglemap.net">embedgooglemap.net</a></div>
							<style>
								.mapouter {
									text-align: right;
									height: 300px;
									width: 300px;
								}

								.gmap_canvas {
									overflow: hidden;
									background: none !important;
									height: 300px;
									width: 300px;
								}
							</style>
						    </div>

					    </div>
                 
    

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>New</th>
      <th>Create</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.new %></td>
        <td><%= quote.create %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<%= render partial: "partial" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Full Name:</strong>
  <%= @quote.full_name %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @quote.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @quote.email %>
</p>

<p>
  <strong>Business Name:</strong>
  <%= @quote.business_name %>
</p>

<p>
  <strong>Quality selected:</strong>
  <%= @quote.quality %>
</p>

<p>
  <strong>Estimate number of elevators needed:</strong>
  <%= @quote.number_elevator %>
</p>

<p>
  <strong>Price per elevators:</strong>
  <%= @quote.elevator_price %> $
</p>

<p>
  <strong>Installation fees:</strong> 
  <%= @quote.installation_price %> $
</p>



<p>
  <strong>Total Estimation:</strong>
  <%= @quote.total_price %> $
</p>