config/routes.rb
Rails.application.routes.draw do
  resources :intervention1s
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/graphql", to: "graphql#execute"
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'RocketElevatorsWebpage_Residential.html' => 'pages#RocketElevatorsWebpage_Residential.html'
  get 'RocketElevatorsWebpage_Corporate.html' => 'pages#RocketElevatorsWebpage_Corporate.html'
  get 'RocketElevatorsWebpage_submission.html' => 'pages#RocketElevatorsWebpage_submission.html'
  get 'login.html' => 'pages#login.html'
  get 'employee' => 'pages#admin/login'
  get "quotes" => "pages#index"
  get "/charts" => 'charts#charts'
  get "google_map" => 'google_maps#index'
  get "/watson" => 'watson#watson'
  get "RockREST" => 'pages#RockRest'
  # get "tasks" => 'intervention1s_controller#buildings'

  resources :google_maps
  resources :transcriptions
  resources :quotes
  resources :leads
  resources :intervention1s  

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_admin!

  
  # GET /charts
  def charts
    
    conn = PG::Connection.open(host: "localhost", port: 5432, dbname: "postgres", user: "postgres", password: "1234")
    # conn = PG::Connection.open(host: "localhost", port: 5432, dbname: "postgres", user: "postgres", password: "1234")

    @data1 = conn.exec ("SELECT business_name, numbers_of_elevators FROM dimcustomers 
      WHERE numbers_of_elevators > 0
      GROUP BY business_name, numbers_of_elevators
      ORDER BY numbers_of_elevators;")
   
    @x1 = @data1.column_values(0)
    @y1 = @data1.column_values(1)

    @data2  = conn.exec('SELECT extract(YEAR FROM created_at) AS YEAR, extract(MONTH FROM created_at) AS MONTH, COUNT(quote_id)
    FROM factquotes
    GROUP BY  YEAR, MONTH
    ORDER BY  YEAR, MONTH')
    @x2 = @data2.column_values(1)
    @y2 = @data2.column_values(2)

    @data3 = conn.exec('SELECT extract(YEAR FROM created_at) AS YEAR, extract(MONTH FROM created_at) AS MONTH, COUNT(id)
    FROM factcontact
    GROUP BY  YEAR, MONTH
    ORDER BY  YEAR, MONTH')
    @x3 = @data3.column_values(1)
    @y3 = @data3.column_values(2)
    
  
  end
  
end
  

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_with(model: chart, local: true) do |form| %>
  <% if chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charts/_partial.html.erb
<div id="wrapper">

		<div id="header" class="dark navbar-toggleable-md sticky clearfix shadow-before-1">

			<!-- TOP NAV -->
			<header id="topNav">
				<div class="container">

					<!-- Mobile Menu Button -->
					<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
						<i class="fa fa-bars"></i>
					</button>

					<!-- BUTTONS -->
					<ul class="float-right nav nav-pills nav-second-main">




					</ul>
					<!-- /BUTTONS -->


					<!-- Logo -->
					<a class="submenu-dark" href="index.html">
						<%= image_tag("R22.png", :alt => "RocketElevator-logo", :class => "img-fluid", :width =>"150", :height =>"60") %>
					</a>

					<div class="navbar-collapse collapse float-right nav-main-collapse">
						<nav class="nav-main">

							<ul id="topMain" class="nav nav-pills nav-main">
								<li>
									<!-- HOME -->
									<a href="/">
										HOME
									</a>

								</li>

								<li>
									<!-- SERVICES -->
									<a href="/#to_services">
										SERVICES
									</a>
									<ul class="dropdown-menu">
										<li><a href="/RocketElevatorsWebpage_Residential.html">Residential offers</a></li>
										<li><a href="/RocketElevatorsWebpage_Corporate.html">Corporate offers</a></li>
										<li><a href="/RocketElevatorsWebpage_submission.html">Submission</a></li>
									</ul>

								<li>
									<!-- PORTFOLIO -->
									<a href="/#to_portfolio">
										PORTFOLIO
									</a>

								<li>
									<!-- NEWS -->
									<a href="/#to_news">
										NEWS
									</a>

								</li>


								<li>
									<!-- CLIENTS -->
									<a href="/#to_clients">
										CLIENTS
									</a>

								</li>

								<li>
									<!-- ADMIN -->
									<a href="/admins">LOGIN</a>

								</li>

								<li>
									<!-- GRAPH -->
									<a href="charts">GRAPH</a>

								</li>

								<li>
									<!-- CONTACT US -->
									<a href="/#footer">
										CONTACT US
									</a>

								</li>


							</ul>

						</nav>
					</div>

				</div>
			</header>
			<!-- /Top Nav -->

		</div>


	<section class="btn btn-xlg btn-primary fs-20 fullwidth m-0 rad-40 p-40 " style="background-image: url('/assets/AdobeStock_103570025.jpeg');">
		<span class="font-lato fs-30" style="color:rgb(300, 300, 300)">
			For the best elevators,
			<strong> Rocket Elevators ! </strong>
		</span>
	</section>

<section class= "dark">


    <div class=" col-md-6 dark">

						
						 

app/views/charts/chart2.html.erb
<%= render partial: "partial" %>
</section>

<section class="dark">
<canvas id="myChart" width="400" height="400"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: 'Numbers of quotes per month',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 3
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>

</section>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<%= render partial: "partial" %>
<p id="notice"><%= notice %></p>

<h1>Charts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charts.each do |chart| %>
      <tr>
        <td><%= link_to 'Show', chart %></td>
        <td><%= link_to 'Edit', edit_chart_path(chart) %></td>
        <td><%= link_to 'Destroy', chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chart', new_chart_path %>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Back', charts_path %>