config/routes.rb
Rails.application.routes.draw do
  resources :intervention1s
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/graphql", to: "graphql#execute"
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'RocketElevatorsWebpage_Residential.html' => 'pages#RocketElevatorsWebpage_Residential.html'
  get 'RocketElevatorsWebpage_Corporate.html' => 'pages#RocketElevatorsWebpage_Corporate.html'
  get 'RocketElevatorsWebpage_submission.html' => 'pages#RocketElevatorsWebpage_submission.html'
  get 'login.html' => 'pages#login.html'
  get 'employee' => 'pages#admin/login'
  get "quotes" => "pages#index"
  get "/charts" => 'charts#charts'
  get "google_map" => 'google_maps#index'
  get "/watson" => 'watson#watson'
  get "RockREST" => 'pages#RockRest'
  # get "tasks" => 'intervention1s_controller#buildings'

  resources :google_maps
  resources :transcriptions
  resources :quotes
  resources :leads
  resources :intervention1s  

end

app/controllers/google_maps_controller.rb
require 'open_weather'
class GoogleMapsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @markers = []
    Building.find_each do |building| 
      if building.id < 21
        # SQL request to take data needed from DB
        address = building.address
        clientName = building.customer.full_name
        batteries = building.batteries.count
        battery_ids = building.battery_ids
        columns = Column.where(battery_id: battery_ids).count
        column_ids = Column.where(battery_id: building.battery_ids).ids
        elevators = Elevator.where(column_id: column_ids).count
        contact = building.building_admin_full_name
        building.batteries.all.each do |battery|
          floor = battery.columns.first.number_of_floor

        # Taking needed data from address
        streetAddress = address.adress
        city = address.city
        country = address.country
        p(streetAddress, city, country)

        # Finding latitude/longitude with address if not already in DB 
        #(If we don't store in DB loading the page is too long)
        if address.longitude.nil?
        address_position =  ([streetAddress, city, country].compact.join(', '))
        results = Geocoder.search(address_position)

        address.latitude = results.first.coordinates[0]
        address.longitude = results.first.coordinates[1]
        address.save!
        end

        # Finding weather with latitude and longitude
        options = { units: "metric", APPID: ENV['weatherkey'] }
        weather = OpenWeather::Current.geocode(address.latitude, address.longitude, options)
        sky = weather['weather'][0]['main']
        temp = weather['main']["temp"]
        
        # Adding data into markers
        @markers << {
        address: address.adress,
        lat: address.latitude, 
        lng: address.longitude,
        customer: clientName,
        batteries: batteries,
        columns: columns, 
        elevators: elevators,
        contact: contact,
        floor: floor,
        sky: sky,
        temp: temp }
        end
      end
    end
  end
end

app/helpers/google_maps_helper.rb
module GoogleMapsHelper
end

app/views/google_maps/_form.html.erb
<%= form_with(model: google_map, local: true) do |form| %>
  <% if google_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(google_map.errors.count, "error") %> prohibited this google_map from being saved:</h2>

      <ul>
      <% google_map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/google_maps/_partial.html.erb
<div id="wrapper">

		<div id="header" class="dark navbar-toggleable-md sticky clearfix shadow-before-1">

			<!-- TOP NAV -->
			<header id="topNav">
				<div class="container">

					<!-- Mobile Menu Button -->
					<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
						<i class="fa fa-bars"></i>
					</button>

					<!-- BUTTONS -->
					<ul class="float-right nav nav-pills nav-second-main">




					</ul>
					<!-- /BUTTONS -->


					<!-- Logo -->
					<a class="submenu-dark" href="index.html">
						<%= image_tag("R22.png", :alt => "RocketElevator-logo", :class => "img-fluid", :width =>"150", :height =>"60") %>
					</a>

					<div class="navbar-collapse collapse float-right nav-main-collapse">
						<nav class="nav-main">

							<ul id="topMain" class="nav nav-pills nav-main">
								<li>
									<!-- HOME -->
									<a href="/">
										HOME
									</a>

								</li>

								<li>
									<!-- SERVICES -->
									<a href="/#to_services">
										SERVICES
									</a>
									<ul class="dropdown-menu">
										<li><a href="/RocketElevatorsWebpage_Residential.html">Residential offers</a></li>
										<li><a href="/RocketElevatorsWebpage_Corporate.html">Corporate offers</a></li>
										<li><a href="/RocketElevatorsWebpage_submission.html">Submission</a></li>
									</ul>

								<li>
									<!-- PORTFOLIO -->
									<a href="/#to_portfolio">
										PORTFOLIO
									</a>

								<li>
									<!-- NEWS -->
									<a href="/#to_news">
										NEWS
									</a>

								</li>


								<li>
									<!-- CLIENTS -->
									<a href="/#to_clients">
										CLIENTS
									</a>

								</li>

								<li>
									<!-- ADMIN -->
									<a href="/admins">LOGIN</a>

								</li>

								<li>
									<!-- GRAPH -->
									<a href="charts">GRAPH</a>

								</li>

								<li>
									<!-- CONTACT US -->
									<a href="/#footer">
										CONTACT US
									</a>

								</li>


							</ul>

						</nav>
					</div>

				</div>
			</header>
			<!-- /Top Nav -->

		</div>


	<section class="btn btn-xlg btn-primary fs-20 fullwidth m-0 rad-40 p-40 " style="background-image: url('/assets/AdobeStock_103570025.jpeg');">
		<span class="font-lato fs-30" style="color:rgb(300, 300, 300)">
			
			<strong>  GOOGLE MAP ! </strong>
		</span>
	</section>


				
				

app/views/google_maps/edit.html.erb
<h1>Editing Google Map</h1>

<%= render 'form', google_map: @google_map %>

<%= link_to 'Show', @google_map %> |
<%= link_to 'Back', google_maps_path %>

app/views/google_maps/index.html.erb
<%= render partial: "partial" %>
<!DOCTYPE html>
<html>
  <head>
    <style>
      #GoogleMap
       {
        height: 700px;
        width: 95%;
       }
       #around {background-color: #232323 }
    </style>
  </head>

<section id="around">
  <center>
  <div id="GoogleMap">
 </div>
  </center>
</section>

  <script>
  var marker_list = [];
    // Taking data from the google map controller
    <% @markers.each do |location| %>
      marker_list.push({
      address: "<%= location[:address] %>",
      lat: <%= location[:lat] %>,
      lng: <%= location[:lng] %>,
      customer: "<%= location[:customer] %>", 
      batteries: "<%= location[:batteries] %>",
      columns: "<%= location[:columns] %> ",
      elevators: "<%= location[:elevators] %> ",
      contact: "<%= location[:contact] %> ",
      floor: "<%= location[:floor] %> ",
      sky: "<%= location[:sky] %> ",
      temp: "<%= location[:temp] %> "
      });
    <% end %> 
    
        // Adding map      
        function initMap() {
        // Mam center location
        var mapCenter = {lat: 46.8139, lng: -81.2080};
        // Center map on North America
        var map = new google.maps.Map(
          document.getElementById('GoogleMap'), {zoom: 4, center: mapCenter});
        var geolocations = marker_list.map(function(location, i){
          var marker = new google.maps.Marker({
          position: location,
          map: map,
          animation:google.maps.Animation.DROP,
          icon: createImage("/assets/rocket_pin.png")
        });

        function createImage(url){
        var image = {
          url: url,
          // This marker is 64 pixels wide by 64 pixels tall.
          scaledsize: new google.maps.Size(64, 64),
          // The origin for this image is 0,0.
          origin: new google.maps.Point(0,0),
          // The anchor for this image is the base of the flagpole at 32,61.
          anchor: new google.maps.Point(32, 61)
          };
          return image;
        }
        var infoWindow = new google.maps.InfoWindow({
          maxWidth: 300
        
        });
        // Content of the infoWindow
        var window = '<h4>' + location.address + '</h4>' +
        '<strong>Customer:</strong> ' + location.customer + '</br>' +
        '<br><strong>Number of Floor:</strong> ' + location.floor + '</br>' +
        '<br><strong>Batteries:</strong> ' + location.batteries + '</br>' +
        '<br><strong>Columns:</strong> ' + location.columns + '</br>' +
        '<br><strong>Elevators:</strong> ' + location.elevators + '</br>' +
        '<br><strong>Contact:</strong> ' + location.contact + '</br>' +
        '<br><strong>Condition:</strong> ' + location.sky + '</br>' +
        '<br><strong>Temperature:</strong> ' + location.temp + ' Celcius';
 
          marker.addListener('click', function() {
          infoWindow.setContent(window)
          infoWindow.open(map, marker);
      });
        // Returning marker for the callback from the URL below
        return marker
      });
  }
  </script>
  
  <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['googlekey'] %>&callback=initMap">
  </script>
 

app/views/google_maps/new.html.erb
<h1>New Google Map</h1>

<%= render 'form', google_map: @google_map %>

<%= link_to 'Back', google_maps_path %>

app/views/google_maps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_google_map_path(@google_map) %> |
<%= link_to 'Back', google_maps_path %>